PROCEDURE_ALIASES = {
    "απευθείας ανάθεση": "direct award",
    "απευθείας αναθέσεις": "direct award",
    "direct award": "direct award",
    "direct award (art. 118/art. 328 of nppl 4412/2016)": "direct award",
    "συνοπτικός": "Summary tender",
    "συνοπτικοί": "Summary tender",
    "συνοπτικούς": "Summary tender",
    "συνοπτικός διαγωνισμός": "Summary tender",
    "ανοικτός": "Open procedure",
    "ανοικτοί": "Open procedure",
    "ανοικτές διαδικασίες": "Open procedure",
    "κλειστός": "Restricted procedure",
    "κλειστοί": "Restricted procedure",
    "κλειστές διαδικασίες": "Restricted procedure",
    "ανταγωνιστικός διάλογος": "Competitive dialogue",
    "ανταγωνιστικούς διαλόγους": "Competitive dialogue",
    "διαπραγμάτευση": "Negotiation without prior publication",
    "διαπραγματεύσεις": "Negotiation without prior publication",
    "διαπραγμάτευση χωρίς δημοσίευση": "Negotiation without prior publication",
    "διαπραγμάτευση χωρίς προηγούμενη δημοσίευση": "Negotiation without prior publication",
    "ανταγωνιστική διαδικασία με διαπραγμάτευση": "Competitive procedure with negotiation",
    "ανταγωνιστική διαπραγμάτευση": "Competitive procedure with negotiation",
    "απευθείας ανάθεση Covid 19": "Direct Award - (Covid 19)",
    "απευθείας αναθέσεις Covid 19": "Direct Award - (Covid 19)",
    "διαπραγμάτευση Covid 19 ": "Negotiation without prior publication - (Covid 19)",
    "διαπραγματεύσεις Covid 19": "Negotiation without prior publication - (Covid 19)",
    "διαπραγμάτευση χωρίς δημοσίευση Covid 19": "Negotiation without prior publication - (Covid 19)",
    "διαπραγμάτευση χωρίς προηγούμενη δημοσίευση Covid 19": "Negotiation without prior publication - (Covid 19)"
}
